name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -race -coverprofile=coverage.out

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Docker Image
        run: |
          docker build -t wallet-service:${{ github.sha }} .

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wallet-service-image
          path: ./wallet-service.tar
        run: docker save wallet-service:${{ github.sha }} -o ./wallet-service.tar

      - name: Push Docker Image to Registry
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          docker tag wallet-service:${{ github.sha }} yourdockerhub/wallet-service:latest
          docker tag wallet-service:${{ github.sha }} yourdockerhub/wallet-service:${{ github.sha }}
          docker push yourdockerhub/wallet-service:latest
          docker push yourdockerhub/wallet-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes Cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl set image deployment/wallet-service wallet-service=yourdockerhub/wallet-service:latest
